# Generated by Django 3.1.14 on 2022-04-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('materialID', models.AutoField(primary_key=True, serialize=False)),
                ('materialQty', models.FloatField()),
                ('materialName', models.CharField(max_length=200)),
                ('threshQty', models.FloatField()),
                ('costPrice', models.FloatField()),
                ('orderedStatus', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('outletID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('outletName', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiterID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('outletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=200)),
                ('itemPrice', models.FloatField()),
                ('itemDescription', models.CharField(max_length=200)),
                ('itemSize', models.BigIntegerField()),
                ('outletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=200)),
                ('customerPhone', models.CharField(max_length=20)),
                ('registrationDate', models.DateField(auto_now=True)),
                ('walletMoney', models.FloatField()),
                ('waiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField(auto_now=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customerinfo')),
                ('orderWaiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.waiter')),
            ],
            options={
                'unique_together': {('orderID', 'customerID')},
            },
        ),
        migrations.CreateModel(
            name='WaiterOrderID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill')),
                ('waiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.waiter')),
            ],
            options={
                'unique_together': {('waiterID', 'orderID')},
            },
        ),
        migrations.CreateModel(
            name='OutletPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=10)),
                ('outletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.outlet')),
            ],
            options={
                'unique_together': {('outletID', 'phoneNo')},
            },
        ),
        migrations.CreateModel(
            name='InventoryDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributorName', models.CharField(max_length=200)),
                ('materialID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory')),
            ],
            options={
                'unique_together': {('materialID', 'distributorName')},
            },
        ),
        migrations.CreateModel(
            name='Creates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQty', models.BigIntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customerinfo')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemdetails')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill')),
            ],
            options={
                'unique_together': {('customerID', 'orderID', 'itemID')},
            },
        ),
    ]
