# Generated by Django 3.1.14 on 2022-04-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creates',
            unique_together={('orderID', 'itemID')},
        ),
        migrations.RemoveField(
            model_name='creates',
            name='customerID',
        ),
    ]
