# Generated by Django 3.1.14 on 2022-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220426_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='orderedStatus',
            field=models.BooleanField(),
        ),
    ]
